server:
   port: 8012
   servlet:
      contextPath: /uaa # web路径

logging: 
    config: classpath:logback-spring.xml

spring: 
    application:
        name: zuul-oauth2-simple

eureka: 
   client:
      serviceUrl:
         defaultZone: http://192.168.101.15:8000/eureka
   instance:
      prefer-ip-address: true