spring: 
   application: 
      name: gateway-server
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true
#   datasource:
#      username: root
#      password: 123456
#     url: jdbc:mysql://192.168.101.213:3306/test
#      driver-class-name: com.mysql.jdbc.Driver
   redis:
      host: 192.168.101.216
      port: 6379
      timeout: 6000
      database: 7
      lettuce:
         pool:
            max-active: 10 # 连接池最大连接数（使用负值表示没有限制）,如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)
            max-idle: 8   # 连接池中的最大空闲连接 ，默认值也是8
            max-wait: 100 # # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException  
            min-idle: 2    # 连接池中的最小空闲连接 ，默认值也是0
         shutdown-timeout: 100ms

server: 
   port: 8889 #网关服务监听 8889 端口

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/

logging: 
   config: classpath:logback-spring.xml
    
#开启端点
management:
   endpoints:
      web:
         exposure:
            include: '*'
   security:
      enabled: false