server: 
   port: 9707
   
logging: 
   config: classpath:logback-spring.xml

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/

---
spring: 
   application: 
      name: zipkin-server

---
# 客户端负载均衡器
ribbon:
   ConnectTimeout: 3000 # 客户端连接超时
   ReadTimeout: 60000 # 客户端读取超时
   MaxAutoRetries: 1 # 当前环境最大重试次数
   MaxAutoRetriesNextServer: 2 # 其他环境最大重试次数
   eureka:
      enabled: true

---
hystrix:
   command:
      default:
         execution:
            timeout:
               enabled: false

---
management:
   metrics:
      web:
         server:
            auto-time-requests: true
