server: 
   port: 8020

logging: 
    config: classpath:logback-spring.xml
    
spring: 
   application: 
        name: eureka-server
   cloud:
      gateway:
         routes:
          - id: test_id
            uri: http://jd.com:80/
            predicates: 
            - Path=/jd/**
            filters:

            