server:
   port: 8001
  
logging: 
   config: classpath:logback-spring.xml

spring: 
   application:
        name: eureka-service
   zipkin:
      base-url: http://192.168.101.15:9707
   sleuth:
      sampler:
         percentage: 1.0
         
eureka:
   client:
      serviceUrl:
         defaultZone: http://192.168.101.15:8000/eureka
      instance: 
         prefer-ip-address: true
--- 
## turbine
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS
  security:
    enabled: false
  boot:
    admin:
      api-path: instances
      auto-registration: true
      url: http://192.168.101.15:9709