server:
   port: 8014

logging: 
   config: classpath:logback-spring.xml

spring: 
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/dingmeikun/tspring-config.git
               username: dingmeikun
               password: a3607311994
               search-paths: DMK_CONFIG_TEST
