spring: 
   application: 
      name: gateway-simple
   redis:
      host: 192.168.101.213
      port: 6379
      password: szdev
      database: 0
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true
         routes:
           - id: region_location
             uri: http://192.168.101.15:9705/business/location
             predicates:
             - name: Path
               args:
                  pattern: /v1/**
             filters:
             - StripPrefix=1
             - name: RequestRateLimiter
               args:
                 key-resolver: '#{@hostAddrKeyResolver}'
                 redis-rate-limiter.replenishRate: 1
                 redis-rate-limiter.burstCapacity: 3
             - name: Hystrix
               args:
                  name: fallbackcmd
                  fallbackUri: forward:/gateway/fallback

hystrix:
   command:
      fallbackcmd:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 2000

feign:
   hystrix:
      enabled: true


server: 
   port: 8889 #网关服务监听 8889 端口

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/

logging: 
    config: classpath:logback-spring.xml