spring: 
    application: 
        name: springcloud-eureka-cluster

logging: 
    config: classpath:logback-spring.xml

info: #项目信息
  app: 
    name: ${spring.application.name}
    #index: http://www.bizport.cn/
    desc: 生产系统服务注册中心

---
## node 1
spring: 
  profiles: eurekaserver1
server: 
  port: 8889
  
eureka: 
    instance: 
        hostname: eurekaserver1
        ipAddress: 10.30.193.206
        instance-id: eurekaserver1:${server.port}
        preferIpAddress: false
    client: 
        registerWithEureka: true #是否将自己注册到eureka server
        fetchRegistry: true #是否从eureka集群获取注册信息
        serviceUrl: 
            defaultZone: http://eurekaserver2:8889/eureka,http://eurekaserver3:8889/eureka,http://eurekaserver4:8889/eureka,http://eurekaserver5:8889/eureka

---
## node 2
spring: 
  profiles: eurekaserver2
server: 
  port: 8889
  
eureka: 
    instance: 
        hostname: eurekaserver2
        ipAddress: 10.47.99.229
        instance-id: eurekaserver2:${server.port}
        preferIpAddress: false
    client: 
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://eurekaserver1:8889/eureka,http://eurekaserver3:8889/eureka,http://eurekaserver4:8889/eureka,http://eurekaserver5:8889/eureka

---
## node 3
spring: 
  profiles: eurekaserver3
server: 
  port: 8889
  
eureka: 
    instance: 
        hostname: eurekaserver3
        ipAddress: 10.30.193.99
        instance-id: eurekaserver3:${server.port}
        preferIpAddress: false
    client: 
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://eurekaserver1:8889/eureka,http://eurekaserver2:8889/eureka,http://eurekaserver4:8889/eureka,http://eurekaserver5:8889/eureka

---
## node 4
spring: 
  profiles: eurekaserver4
server: 
  port: 8889
  
eureka: 
    instance: 
        hostname: eurekaserver4
        ipAddress: 10.24.39.42
        instance-id: eurekaserver4:${server.port}
        preferIpAddress: false
    client: 
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://eurekaserver1:8889/eureka,http://eurekaserver2:8889/eureka,http://eurekaserver3:8889/eureka,http://eurekaserver5:8889/eureka

---
## node 5
spring: 
  profiles: eurekaserver5
server: 
  port: 8889
  
eureka: 
    instance: 
        hostname: eurekaserver5
        ipAddress: 10.24.38.88
        instance-id: eurekaserver5:${server.port}
        preferIpAddress: false
    client: 
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: http://eurekaserver1:8889/eureka,http://eurekaserver2:8889/eureka,http://eurekaserver3:8889/eureka,http://eurekaserver4:8889/eureka
            