server: 
   port: 9706
   
logging: 
   config: classpath:logback-spring.xml

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/

spring: 
   application: 
      name: zipkin-client
   zipkin:
      base-url: http://localhost:9707
   sleuth:
      sampler:
         percentage: 1.0