spring:
   main:
      allow-bean-definition-overriding: true
   application:
      name: admin-server
   security:
      user:
         name: admin
         password: 123456
      enabled: false
      basic:
         enabled: false
   boot:
      admin:
         routes:
            endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream,loggers,auditevents

server: 
   port: 9708

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/
   eureka:
      instance:
         lease-renewal-interval-in-seconds: 10
         metadata-map:
           user.name: admin
           user.password: xy123456

logging: 
    config: classpath:logback-spring.xml
    
