spring: 
   application: 
      name: admin-server

server: 
   port: 9000

eureka:
   client:
      service-url: #指定注册中心的地址，以便使用服务发现功能
         defaultZone: http://localhost:8000/eureka/

logging: 
    config: classpath:logback-spring.xml