server:
  port: 8008

logging: 
    config: classpath:logback-spring.xml

spring: 
    application:
        name: zuul-simple

eureka: 
   client:
      serviceUrl:
         defaultZone: http://192.168.101.15:8000/eureka
   instance:
      prefer-ip-address: true