---
# eureka注册中心配置
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8000/eureka/
feign:
    hystrix:
        enabled: true

hystrix:
   command:
      fallbackcmd:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 2000

logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: debug
--- 
# 开启端点
management:
    endpoints:
        web:
            exposure:
                include: '*'
    security:
        enabled: false
server:
    port: 9706

--- 
# gateway配置
spring:
    application:
        name: gateway-server
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lowerCaseServiceId: true
    sleuth:
        sampler:
            probability: 1.0
    zipkin:
        base-url: http://192.168.101.15:9707
        service:
            name: gateway-server
